### ISSUE TITLE
Extra data after last expected column

### ISSUE THREAD

**Issue by herrmaak** [anthonydb/practical-sql#12]
You reference this error in the book when trying to import the US census but do not indicate how to resolve. I am receiving this error: extra data after last expected column
Context: copy us_counties_2010, line 2: Autauga county
Error proceed with exact info in your book.

How do you resolve ?

**Comment by anthonydb** [comment]
Hello, thanks for writing. I assume you're having trouble importing the Census data using the `COPY` statement in Listing 4-3.

Would you please paste the code you're using here? Also, please say which operating system you're using.

Thanks.
