### ISSUE TITLE
Chapter 4 Exporting

### ISSUE THREAD

**Issue by anthonysim** [anthonydb/practical-sql#14]
When I try Listing 4-8 on page 52

COPY us_counties_2010
TO 'C:\us_counties_export.txt'
WITH (FORMAT CSV, HEADER, DELIMITER '|')

I get the following error message:
ERROR: could not open file "C:\us_counties_export.txt" for writing: Permission denied 
HINT: COPY TO instructs the PostgreSQL server process to write a file. You may want a client-side facility such as psql's \copy. SQL state: 42501

I have no idea how to rectify this situation.

**Comment by anthonydb** [comment]
Hi, @anthonysim ...

This can happen if PostgreSQL doesn't have rights to the folder where you're either reading or writing a file. I would suggest two things:

1. Create a folder on your C: drive for file output.
2. Follow the directions in the NOTE on page xxviii of the book's Introduction that explains how to grant permission to folders in Windows. You may have done this already with the folder that contains the code and date from GitHub.

Please let me know if that solves the issue. Also, let me know which version of Windows you're on.

**Comment by anthonysim** [comment]
Thanks @anthonydb, I appreciate it! It worked and I am using Windows 10.

**Comment by anthonydb** [comment]
Glad to hear it. I'll keep this issue open in case others run into the same question.

**Comment by PaulusJS** [comment]
Hi @anthonydb 

I am having a similar issue concerning but with the import of the CSV file (see error message below). 

I am trying to import the file from a new folder I created on my Mac desktop for which I changed the permissions to write & read (although permission to read should be sufficient) and I did the same for the CSV file itself (read & write). 

No matter what I try I still get the same error message: 

ERROR:  could not open file "/namepath/us_counties_2010.csv" for reading: Permission denied
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
SQL state: 42501

**Comment by anthonydb** [comment]
Hi, @PaulusJS,

Unusual for a Mac. How did you install PostgreSQL?

**Comment by crawfordniche** [comment]
Is it just me, or are land_areas in the CSV floats whaereas land_area is data type bigint?  Perhaps that's for didactic purpose and I just need to keep reading?

**Comment by Nightsurf** [comment]
Hello, Idk if I'm going crazy but I don't see a downloadable CSV file, it just uploads to a site there the data resides, not an actual file that I can download

**Comment by Nightsurf** [comment]
Can't COPY the file and it's driving me bananas. The directory exists!!

COPY us_counties_2010
FROM 'C:\Users\innad\Desktop\us_counties_2010.csv'
WITH (FORMAT CSV, HEADER);


ERROR:  could not open file "C:\Users\innad\Desktop\us_counties_2010.csv" for reading: **No such file or directory**
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
SQL state: 58P01

**Comment by anthonysim** [comment]
I have no idea, but the problem just came back for me. I updated to postgre SQL and the same thing is happening again.

**Comment by ayangupta-dotcom** [comment]
> When I try Listing 4-8 on page 52
> 
> COPY us_counties_2010 TO 'C:\us_counties_export.txt' WITH (FORMAT CSV, HEADER, DELIMITER '|')
> 
> I get the following error message: ERROR: could not open file "C:\us_counties_export.txt" for writing: Permission denied HINT: COPY TO instructs the PostgreSQL server process to write a file. You may want a client-side facility such as psql's \copy. SQL state: 42501
> 
> I have no idea how to rectify this situation.
Hey have you rectify this situation ?

**Comment by anthonydb** [comment]
@ayangupta-dotcom Please take a look at my earlier responses in this ticket or to my answer on https://github.com/anthonydb/practical-sql/issues/32
