### ISSUE TITLE
Chapter 7 Listing 8-1 Import Error

### ISSUE THREAD

**Issue by anthonysim** [anthonydb/practical-sql#15]
# Practical SQL Issue Template

Having trouble with data, code, or exercises in Practical SQL? I'm glad to help. Please answer these questions, and I'll typically reply within one business day.

Please include the chapter number in your issue title. For example: "Chapter 13: Regular Expression Question"

### General

**What's your operating system (e.g. Windows 10, macOS Mojave, Ubuntu, etc.)?**
Windows 10

**Did you install PostgreSQL and pgAdmin according to the steps on page xxviii of the book's Introduction? If not, please describe your installation.**
Yes.

**Did you download the book's code examples and data from GitHub using the directions on page xxvii of the Introduction? If not, please describe how you loaded the material on your computer.**
Yes

### Issue or Question

**Chapter, page and code listing number:**
Chapter 7 Listing 8-1 on page 115

**Describe the issue or your question. Please include any error messages:**
When trying to run the code for listing 8-1 I get the following error message:

ERROR: invalid byte sequence for encoding "UTF8": 0xc9 0x52 CONTEXT: COPY pls_fy2014_pupld14a, line 7400 SQL state: 22021

I believe the issue is because of the accents over certain names like Munoz will have Muñoz. I tried to change some of the names to remove the accents, but there were too many. 

I was wondering if there is a way to change them all somehow or if I can do something on PostgreSQL to accept the accented names.

**Comment by anthonydb** [comment]
@anthonysim Hi, thanks for the report. You are right that it's related to encoding. Two questions:

1. By any chance, did you open the CSV in Excel or a text editor to view its contents before you tried the import? Sometimes on Windows, doing so changes the file encoding. If you did, please download a fresh copy from GitHub and try again.
2. Are you running your code in pgAdmin or via psql?

**Comment by anthonysim** [comment]
Hello @anthonydb !

1. No I didn;t open the CSV in Excel or a text editor before I tried to import. I opened it after I realized it didn't import.

2. I am running the code in pgadmin.

I will download the data again and give it another go!

**Comment by anthonydb** [comment]
Sounds good -- let me know how it goes @anthonysim!

**Comment by anthonysim** [comment]
Hi @anthonydb , 

I downloaded a fresh copy and did the process all over again and it worked like a charm!

All is good!

**Comment by anthonydb** [comment]
@anthonysim -- excellent! I'll close this now. Let me know if you have any other questions!
