### ISSUE TITLE
chapter 4 retrieve census .csv file

### ISSUE THREAD

**Issue by brentdata** [anthonydb/practical-sql#20]
# Practical SQL Issue Template

Having trouble with data, code, or exercises in Practical SQL? I'm glad to help. Please answer these questions, and I'll typically reply within one business day.

Please include the chapter number in your issue title. For example: "Chapter 13: Regular Expression Question"

### General

**What's your operating system (e.g. Windows 10, macOS Mojave, Ubuntu, etc.)?**

**Did you install PostgreSQL and pgAdmin according to the steps on page xxviii of the book's Introduction? If not, please describe your installation.**

**Did you download the book's code examples and data from GitHub using the directions on page xxvii of the Introduction? If not, please describe how you loaded the material on your computer.**

### Issue or Question

**Chapter, page and code listing number:**

**Describe the issue or your question. Please include any error messages:**

When attempting to copy the census file from my desktop i get the following error message: 

Here is the SQL statement:  COPY us_counties_2010
FROM 'C:\users\Michael\Desktop\us_counties_2010.csv'
WITH (FORMAT CSV, HEADER);

Here is the result:

ERROR: could not open file "C:\users\Michael\Desktop\us_counties_2010.csv" for reading: Permission denied HINT: COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy. SQL state: 42501

I thought it was a Windows 10 permissions issue and set up my folders for access by everyone but it still errored out. Then i asked Windows support and they said it was an issue with PostgreSQL. 

Thanks for your help.

**Comment by anthonydb** [comment]
Hi, @brentdata,

I would suggest the following:

1. Follow the instructions on page xxvii of the book's Introduction, in the section "Using the Book's Code Examples," to download this entire repository to your machine.
2. Unzip the files and copy all the folders and files into a folder on your Desktop.
3. Follow the directions in the NOTE on the same page of the book to set the permission of that folder.
4. Finally, on some Windows systems, the case of the file path names may matter, so make sure the path you provide to the CSV file matches the spelling and case.

That should solve the issue. Let me know here.

Thanks for reading Practical SQL!

**Comment by brentdata** [comment]
Thanks Anthony! Will give it a try this wkd.

**Comment by brentdata** [comment]
It worked perfectly. Thanks!

**Comment by anthonydb** [comment]
Great!

**Comment by jdavisbsphysics** [comment]
Chapter 14: Census CSV Import Issue

[Using Windows 7, I installed PostgreSQL and pgAdmin
with steps described starting on p. 14 of the attached
document. 
[Java Development Environment Installation Guide.pdf](https://github.com/anthonydb/practical-sql/files/3167427/Java.Development.Environment.Installation.Guide.pdf)


I have done some things with the User accounts on
my pc that might affect how I'm able to use psql 
(psql says the password isn't correct)--but I've been 
able to use pgAdmin4 fine with your book, until 
importing the census table.]

I was able to import the file populating the census table you
had us create after downloading the book's entire archive 
(as you've suggested). The file there looks a little odd with the 
XML extension, according to Windows Explorer; I was looking for
something ending in .csv. 

My previous failures ended up with a message in
pgAdmin4 that 'second column is missing data: state_usa_something'.

I got basically the same error message when I even deleted
the entire second column (for state abbreviations) from the 
table and from the CSV header and from the first row of the
CSV file--and got rid of all the rest of the rows in the file.
The message in pgAdmin4 was still 'second column is missing 
data: [whatever the originally third column was]'. 

I'd saved the cs file in those errant trials like this:
clicking on the us_counties_2010.csv link from your Chapter 4
repository, then right-clicking the webpage that followed and 
selecting "Save As," which gave me a file that ended in .csv but
was listed as a text file in my Windows Explorer. 

Anyway, thanks for your care for everyone using your work. 
Overall, your book is literally the only pgAdmin4 tutorial I've found
coherent. And it's interesting, definitely.

EXTREMELY Grateful,

J

**Comment by anthonydb** [comment]
@jdavisbsphysics 

Hi, 

The first thing to confirm is that you followed the instructions on page xxvii of the book's Introduction, in the section "Using the Book's Code Examples," to download this entire repository to your machine. It should download as a .zip file, which you then can uncompress.

Please let me know if you followed those directions. If not, please give that a try and let me know the results.

**Comment by jdavisbsphysics** [comment]
I did follow those directions and have successfully retrieved the census file ("I was able to import the file populating the census table you had us create after downloading the book's entire archive (as you've suggested))."

Since downloading the whole ZIP file was optional ("At GitHub, you should see a “Clone or Download” button that gives you the option to download a ZIP file with all the materials"), I had first chosen to try downloading just the census CSV file. I wrote mainly to note the difficulty I had with that method--and to thank you.

Thanks Again,

J

**Comment by anthonydb** [comment]
Great, glad it's all sorted.
