### ISSUE TITLE
Chapter 8: Using GROUP BY with count()

### ISSUE THREAD

**Issue by stephanie-y** [anthonydb/practical-sql#21]
Inconsistencies between code in listing 8 - 9 github respository and textbook:
github code uses order by count(stabr) while textbook lists order by count(*)

**Comment by anthonydb** [comment]
@stephanie-y Thank you for your eagle eye! I have made the fix via https://github.com/anthonydb/practical-sql/commit/ba277329ebeb575e7e44cb16291cee706ab4c3d5
