### ISSUE TITLE
Pg. 50; Listing 4-6 returning with "42601" parameter error

### ISSUE THREAD

**Issue by esleipness** [anthonydb/practical-sql#22]
# Practical SQL Issue Template

Having trouble with data, code, or exercises in Practical SQL? I'm glad to help. Please answer these questions, and I'll typically reply within one business day.

Please include the chapter number in your issue title. For example: "Chapter 13: Regular Expression Question"

### General

**What's your operating system (e.g. Windows 10, macOS Mojave, Ubuntu, etc.)?**
Windows10
**Did you install PostgreSQL and pgAdmin according to the steps on page xxviii of the book's Introduction? If not, please describe your installation.**
Yes
**Did you download the book's code examples and data from GitHub using the directions on page xxvii of the Introduction? If not, please describe how you loaded the material on your computer.**
Yes
### Issue or Question
4.6 returning with "42601" parameter error  Pg. 50
**Chapter, page and code listing number:**

**Describe the issue or your question. Please include any error messages:**

**Comment by anthonydb** [comment]
Hi, @esleipness ... 

Some follow-up questions:

**Which versions of PostgreSQL and pgAdmin 4 are you using?**

**Would you please copy your code and paste it here so I can review?**

Thanks!
Anthony

**Comment by esleipness** [comment]
I didn't save the original code and now my query is working; it must have been user error. ;)

**Comment by esleipness** [comment]
It's 12.

**Comment by anthonydb** [comment]
Hey, it happens :-)
Glad it's working now. Reach out again if you run into any other issues, and thanks for reading the book!
