### ISSUE TITLE
Median taxi trip calculation too complicated

### ISSUE THREAD

**Issue by jberkus** [anthonydb/practical-sql#3]
For chapter 11, in the NYC median taxi trip calculation, you use a dodge with epoch which is unnecessary and makes the query more complicated to read.  Please replace with the following:

SELECT
    date_part('hour', tpep_pickup_datetime),
    percentile_cont(.5)
        WITHIN GROUP (ORDER BY
                               tpep_dropoff_datetime - tpep_pickup_datetime) AS "median_trip"
FROM nyc_yellow_taxi_trips_2016_06_01
GROUP BY date_part('hour', tpep_pickup_datetime)
ORDER BY date_part('hour', tpep_pickup_datetime);

**Comment by anthonydb** [comment]
Thanks, @jberkus ... will change when your notes on that chapter make it to me.

**Comment by anthonydb** [comment]
Changed in https://github.com/anthonydb/practical-sql/commit/05622ce624b19bb77d30c0db55d3c943877362b6

Thanks again!
