### ISSUE TITLE
Chapter 3 Listing 3.1

### ISSUE THREAD

**Issue by petelg** [anthonydb/practical-sql#30]
I got an error, access denied. PostgreSQL can't write to the file.

**Comment by anthonydb** [comment]
Hi, @petelg -- It will be easier to help you if you let me know which operating system you're using.

**Comment by petelg** [comment]
It is Windows. I changed the file path to 'C:\Users\PC\typetest.txt'

**Comment by anthonydb** [comment]
Hi,

Please take a look at the NOTE at the bottom of page xxvii in the book's Introduction. You must provide permission for PostgreSQL to access a folder. I suggest downloading the code into a folder in an easy-to-find folder, then set the permission as per the NOTE on that page. After that, you should be able to both read and write files.

**Comment by petelg** [comment]
Oh, I missed that. Now it works. Thanks!

**Comment by anthonydb** [comment]
Awesome -- please reach out here with any other questions, and thanks for reading!
