### ISSUE TITLE
CHAPTER 8

### ISSUE THREAD

**Issue by piotrmichaljaniszewski** [anthonydb/practical-sql#41]
Hello i have problem with Chapter 8: Table Design That Works for You
i cant create index , I see this message :

ERROR:  invalid byte sequence for encoding "UTF8": 0x00
CONTEXT:  COPY pls_fy2014_pupld14a, line 1
SQL state: 22021

Can you help me ? thanks a lot

**Comment by anthonydb** [comment]
Hi, what is your operating system?

Also, would you please run these two commands and report back the results?

`SHOW client_encoding;`
 
`SHOW server_encoding;`

**Comment by piotrmichaljaniszewski** [comment]
hi, i have macos
![75B68B9C-EEC3-4C08-8681-B38892F0EB17_4_5005_c](https://user-images.githubusercontent.com/112071773/204391896-02de8aad-b455-4b54-8487-ae1b4ab44f54.jpeg)
![0C26C4F1-E4CD-45E0-AB9B-74F01660BAE7_4_5005_c](https://user-images.githubusercontent.com/112071773/204391940-663c95d8-441b-458e-aa6e-cb2c69dec0fb.jpeg)

**Comment by anthonydb** [comment]
OK, those settings are the same as on my Mac. I just downloaded the file, created the table and imported it. Would you please re-download a fresh copy of the file, do not touch it with any text editor, and try again?

**Comment by piotrmichaljaniszewski** [comment]
now everything works, I checked chapter 9 and it's ok too. 
thank you for your help. 
Greetings from Poland

**Comment by anthonydb** [comment]
Excellent! Enjoy the book!
