### ISSUE TITLE
Ch. 4 Copy | Mac OS | Error 42P01

### ISSUE THREAD

**Issue by KingdomAnimalia** [anthonydb/practical-sql#42]
Please include the chapter number in your issue title. For example: "Chapter 13: Regular Expression Question"

Ch. 4:  Importing and Exporting Data

**What's your operating system (e.g. Windows 10, macOS Catalina, Ubuntu, etc.)?**

MacOS Ventura 13.1

**Did you install PostgreSQL and pgAdmin according to the steps on page xxviii of the book's Introduction? If not, please describe your installation.**

Yes.  

**Which versions of PostgreSQL and pgAdmin 4 are you using? If you aren't sure, for PostgreSQL run the SQL command `SELECT version();` and for pgAdmin 4, navigate to "About pgAdmin 4" under the "Help" menu.**

PostgreSQL is 15.1 and pgAdmin is 6.18

**Did you download the book's code examples and data from GitHub using the directions on page xxvii of the Introduction? If not, please describe how you loaded the material on your computer.**

Yes, I followed the instructions. 

### Issue or Question

**Chapter, page and code listing number:**

Ch. 4, pg 47, listing 4-3

**Describe the issue or your question:**

This seems like the most simple action we've been asked to perform, and yet...I keep getting the 42P01 error..Please help....I've scoured the internet (and all the prior questions) and cannot resolve this :( Thank you

**Please paste the code and error message here. It's OK to alter identifying info such as a folder name**

ERROR: relation "us_counties_2010" does not exist 
SQL state: 42P01

**Comment by KingdomAnimalia** [comment]
Please help. Thanks in advance.

**Comment by anthonydb** [comment]
Hi, two questions:

1) Did you create the table `us_counties_2010`?

2) Confirm that you are using the 1st edition of the book and not the 2nd edition.

Thanks

**Comment by KingdomAnimalia** [comment]
Hello, 

1. ...oh my gosh that's 100% the issue. Everything is fine and works perfectly now. Thanks so much!
2.  1st edition

Thanks so much for the hint! Literally can't believe I glossed over that part.

**Comment by anthonydb** [comment]
Great!
