### ISSUE TITLE
Chapter 14: Analyzing Spatial Data no geom column

### ISSUE THREAD

**Issue by Pelil-tepes** [anthonydb/practical-sql#43]
Having trouble with data, code, or exercises in Practical SQL, 1st Edition? I'm glad to help. Please answer these questions, and I'll typically reply within one to two business days.

Please include the chapter number in your issue title. For example: "Chapter 13: Regular Expression Question"

### General
Please answer all of these as they're essential for troubleshooting.

**What's your operating system (e.g. Windows 10, macOS Catalina, Ubuntu, etc.)?**

Windows 11 - SQL server is running on Linux

**Did you install PostgreSQL and pgAdmin according to the steps on page xxviii of the book's Introduction? If not, please describe your installation.**

Server installed in a docker container. PGAdmin installed on Windows PC.

**Which versions of PostgreSQL and pgAdmin 4 are you using? If you aren't sure, for PostgreSQL run the SQL command `SELECT version();` and for pgAdmin 4, navigate to "About pgAdmin 4" under the "Help" menu.**

PGAdmin 8.7 Postgresql 16.3-1

**Did you download the book's code examples and data from GitHub using the directions on page xxvii of the Introduction? If not, please describe how you loaded the material on your computer.**

Yes

### Issue or Question

**Chapter, page and code listing number:**

Chapter 14 page 260 listing 14-14

**Describe the issue or your question:**

After following the instructions to import the shape file, I ran the code listed and I'm getting a no geom column error. I confirmed there is no geom column by looking at the schema.

**Please paste the code and error message here. It's OK to alter identifying info such as a folder name**

SELECT ST_AsText(geom)
FROM us_counties_2010_shp
LIMIT 1;

ERROR:  column "geom" does not exist
LINE 1: SELECT ST_AsText(geom)
                         ^ 

SQL state: 42703
Character: 18

![image](https://github.com/user-attachments/assets/4d12458f-9b72-437e-9218-336c6373b9b5)

**Comment by anthonydb** [comment]
@Pelil-tepes I had this issue come up once before with another reader. The cause was that they had moved only the file with the `.shp` extension into the folder they were importing from. Do you have all the associated files in the same folder?

**Comment by Pelil-tepes** [comment]
They appear to be, I unzipped to the same location. 
![image](https://github.com/user-attachments/assets/fae0a850-5d47-4ea6-be0d-b98a080c83af)

**Comment by Pelil-tepes** [comment]
I did notice one possible issue. I am unable to import the data unless I select the "Load only attribute (dbf) data". Could this possibly strip the geom? 

![image](https://github.com/user-attachments/assets/5a6d8cbf-3f17-453c-9ccb-205fb3726ba1)

**Comment by anthonydb** [comment]
Yes, I believe that would indeed be the cause of no `geom` column because it's not reading the geometry from the file with the `.shp` extension. What kind of error do you get when you check that box?

I can fire up my Windows machine and try to replicate the issue.

**Comment by Pelil-tepes** [comment]
If I don't check the box, I get a Shapefile import failed. There is no other information displayed.

[cid:b0858ee3-eb04-4618-83b7-82d30cd6bc7a]

________________________________

**Comment by anthonydb** [comment]
@Pelil-tepes Please confirm you ran `CREATE EXTENSION postgis;` on your database. You can check if PostGIS is installed by running the query `SELECT postgis_full_version();`

**Comment by Pelil-tepes** [comment]
I'm showing that postgis exists. However, I get an error trying to pull the version.

[cid:cdd63129-dfc9-4d21-b65f-ecc3689cf4e0]

[cid:17fa1cc6-66ef-402a-948b-b452a2504741]


________________________________

**Comment by anthonydb** [comment]
If you added screengrabs, they're not displaying. Please upload them to this ticket so I can see the error.

**Comment by Pelil-tepes** [comment]
![image](https://github.com/user-attachments/assets/b7765ccb-6b28-402b-a631-4c6bf39076c7)

**Comment by anthonydb** [comment]
OK, I'm going to assume this is an artifact of running in a Docker container. In the book, I specify install steps, and I am confident that if PostgreSQL and pgAdmin are installed according to the book that all will work. I unfortunately can't support alternate installations.

Is it possible for you to install PostgreSQL/PostGIS as instructed in the book?

**Comment by Pelil-tepes** [comment]
I have made modifications to my docker file and confirmed it is working. I did install shp2sql to my windows PC and connect to the server using the IP and port for the SQL server.  Hopefully, this information will be useful to others. I appreciate the assistance.

`version: '3.9'
services:  
  db:
    container_name: PostgreSQL
    image: postgis/postgis
    mem_limit: 256m
    cpu_shares: 768

    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "bmmt_DB", "-U", "root"]
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_DB
    volumes:
      - /volume1/docker/postgresql:/var/lib/postgresql/data:rw
    ports:
      - 2665:5432
    restart: on-failure:5
`
