### ISSUE TITLE
Chapter 8: Try It Yourself  Question 2

### ISSUE THREAD

**Issue by jmpemberton** [anthonydb/practical-sql#44]
I am working on question 2 in chapter 8's Try It Yourself section but I keep getting no returns other than the header row; no errors either.

**MY CODE**

CREATE TABLE regions (
	obereg varchar(2) NOT NULL,
	regname varchar(15) NOT NULL
);

INSERT INTO regions (obereg, regname)
VALUES
	('1', 'Northeast'),
	('2', 'East'),
	('3', 'Midwest'),
	('4', 'Plains'),
	('5', 'South'),
	('6', 'Southwest'),
	('7', 'Rockies'),
	('8', 'Pacific'),
	('9', 'Territories');

SELECT * FROM regions;

**RESULT**
obereg | regname
1 | Northeast
2 | East
3 | Midwest
4 | Plains
5 | South
6 | Southwest
7 | Rockies
8 | Pacific
9 | Territories

Alright, the third table has been successfully created and populated, now I try to use it for the 2014/2019 visits difference SQL that we created earlier in the chapter.

SELECT r.regname AS "Region",
	   sum(pls09.visits) AS "2009 Visits",
	   sum(pls14.visits) AS "2014 Visits",
	   round( (CAST(sum(pls14.visits) AS decimal(10,1)) - sum(pls09.visits)) / sum(pls09.visits) * 100, 2 ) AS "% Change"
FROM pls_fy2014_pupld14a pls14
INNER JOIN pls_fy2009_pupld09a pls09  ON pls14.fscskey = pls09.fscskey
INNER JOIN regions r ON pls14.obereg = r.obereg
WHERE pls14.visits >= 0 AND pls09.visits >= 0
GROUP BY r.regname
ORDER BY "% Change" DESC;

This SQL does not encounter an error, but I get nothing but the header row in the results.
![image](https://github.com/user-attachments/assets/f015b573-25ff-409f-b9c2-227bbe54abb1)

I checked out your code in the provided materials and other than naming, our code matches up. I have no clue what I'm doing wrong here.

**Comment by anthonydb** [comment]
Hi, @jmpemberton,

The `obereg` codes in the `pls_fy2014_pupld14a` table have a leading zero -- e.g., `01`, `02`, `03`, etc. In the `regions` table you created, your codes omit that leading zero. As a result, the join finds no matching values.

Try recreating your `regions` table with correctly formatted codes and see if that works. You also can peek at my solutions to the Try It Yourself problems here:

https://github.com/anthonydb/practical-sql/blob/main/Try_It_Yourself/Try_It_Yourself.sql

**Comment by jmpemberton** [comment]
That worked great. Thank you so much. 

The reason that I did not use the leading zeros in my INSERT code for the obereg field is because I did not see leading zeros in the 2014 csv file that you provided. I guess that the varchar(2) should've been a big clue to use a leading zero for the field.

Anyway, it's working as it should now. Thank you for your time.

**Comment by anthonydb** [comment]
Glad it worked out.

If you opened the CSV file with Excel or another spreadsheet program, then it will automatically remove the leading zeros on anything that looks like a number. For that reason, especially in the second edition, I recommend inspecting CSV files with a text editor.
